spring:
  application:
    name: info-collect-tool
  # 单个文件大小限制
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

  datasource:
    url: jdbc:sqlite:info-collect.db
    driver-class-name: org.sqlite.JDBC
    username: ""
    password: ""
  sql:
    init:
      mode: always



mybatis:
  mapper-locations: classpath:mapper/*.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

upload:
  dir: uploads/

allowed:
  extensions:
    - xlsx
    - xls


