spring:
  application:
    name: info-collect-tool
  # 单个文件大小限制
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

  datasource:
    url: jdbc:sqlite:db/info-collect.db
    driver-class-name: org.sqlite.JDBC
    username: ""
    password: ""
  sql:
    init:
      mode: always

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  file:
    name: logs/info-collect-tool.log
  level:
    root: INFO


springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

app:
  scheduler:
    enabled: true
    # 定时任务执行间隔 180秒
    duration: 180
  upload:
    allowed-extensions: xlsx,xls

