spring:
  application:
    name: info-collect-tool
  # 单个文件大小限制
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

