name: Publish Docker image

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  docker_build_and_push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: claydocker/info-collect-tool

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy_dev:
    name: "Deploy"
    needs: docker_build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: publish with docker compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
#          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker pull claydocker/info-collect-tool:main
            docker run -d -p 8080:8080 --name info-collect-tool \
              -v /info-collect-tool/logs:/app/logs \
              -v /info-collect-tool/uploads:/app/uploads \
              claydocker/info-collect-tool:latest